### ISSUE TITLE
在XML中打“.”会报错

### ISSUE THREAD

**Issue by Greenplumwine** [wuzhizhan/free-idea-mybatis#102]
`java.lang.NoSuchMethodError: 'void com.intellij.codeInsight.AutoPopupController.runTransactionWithEverythingCommitted(com.intellij.openapi.project.Project, java.lang.Runnable)'
	at com.wuzhizhan.mybatis.action.MybatisTypedHandler.autoPopupParameter(MybatisTypedHandler.java:46)
	at com.wuzhizhan.mybatis.action.MybatisTypedHandler.checkAutoPopup(MybatisTypedHandler.java:22)
	at com.intellij.codeInsight.editorActions.TypedHandler.lambda$null$0(TypedHandler.java:161)
	at com.intellij.codeInsight.editorActions.TypedHandler.callDelegates(TypedHandler.java:230)
	at com.intellij.codeInsight.editorActions.TypedHandler.lambda$execute$4(TypedHandler.java:161)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$3(CaretModelImpl.java:355)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:457)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:347)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:337)
	at com.intellij.codeInsight.editorActions.TypedHandler.execute(TypedHandler.java:152)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:75)
	at com.intellij.codeInsight.template.emmet.EmmetPreviewTypedHandler.execute(EmmetPreviewTypedHandler.java:39)
	at com.intellij.codeInsight.editorActions.AutoFormatTypedHandler.executeOriginalHandler(AutoFormatTypedHandler.java:167)
	at com.intellij.codeInsight.editorActions.AutoFormatTypedHandler.execute(AutoFormatTypedHandler.java:94)
	at com.intellij.execution.impl.ConsoleViewImpl$MyTypedHandler.execute(ConsoleViewImpl.java:1175)
	at com.intellij.openapi.editor.impl.DefaultRawTypedHandler$1.run(DefaultRawTypedHandler.java:55)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:885)
	at com.intellij.openapi.editor.impl.DefaultRawTypedHandler.execute(DefaultRawTypedHandler.java:49)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl$MyRawTypedHandler.execute(EditorFactoryImpl.java:289)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$0(TypedAction.java:133)
	at com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:28)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:133)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedNormally(EditorImpl.java:1291)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1274)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:3349)
	at com.intellij.openapi.editor.impl.EditorImpl$7.keyTyped(EditorImpl.java:1104)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6606)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2849)
	at java.desktop/java.awt.Component.processEvent(Component.java:6428)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:878)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1148)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1017)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:843)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:40)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4907)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:832)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by itszhengkun** [comment]
同样遇到了，idea 版本是2019.3

**Comment by Howar6htb** [comment]
同，idea 版本也是2019.3

**Comment by GmwEnterprise** [comment]
same question.

**Comment by liangling627** [comment]
same question.

**Comment by UnNous** [comment]
same question.

**Comment by winsoar** [comment]
same question.

**Comment by fallingmoon** [comment]
same question.

**Comment by Blulotus2019** [comment]
same question.

**Comment by Downstream1998** [comment]
According to [Incompatible Changes in IntelliJ Platform and Plugins API 2019.*](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/api_changes/api_changes_list_2019.html), method `void com.intellij.codeInsight.AutoPopupController.runTransactionWithEverythingCommitted(Project, Runnable)` has been removed in Intellij Platform version 2019.3.

I have found [the place](https://github.com/wuzhizhan/free-idea-mybatis/blob/master/src/main/java/com/wuzhizhan/mybatis/action/MybatisTypedHandler.java#L46) where this method is called.

I wonder if someone can change it to call `com.intellij.codeInsight.AutoPopupControllerImpl.runTransactionWithEverythingCommitted(Project, Runnable)`, solve this issue and make a pull request?

**Comment by a2020883119** [comment]
同样问题，无法打出~

**Comment by tinynemo** [comment]
临时解决办法：
- 1. 下载代码，修改build.gradle, 升级其IDEA库到2019.1:
```groovy
intellij {
    version = 'IU-2019.1'
    pluginName = 'free-idea-mybatis'
    plugins = ['coverage', 'Spring', 'DatabaseTools']
    intellij.updateSinceUntilBuild false
}
```
- 2. 修改`com.wuzhizhan.mybatis.action.MybatisTypedHandler.autoPopupParameter`:
```java
    private static void autoPopupParameter(final Project project, final Editor editor) {
        AppUIExecutor.onUiThread().later().withDocumentsCommitted(project).inTransaction(project).execute(new Runnable() {
            @Override
            public void run() {
                new CodeCompletionHandlerBase(CompletionType.BASIC).invokeCompletion(project, editor, 1);
            }
        });
    }
```

- 3. gradle jar可以成功生成jar包，安装到idea

这样可以生成jar包，安装到idea后暂时可以正常使用。**但是build还是会失败**

**Comment by txwdzxq** [comment]
> 临时解决办法：
> 
> * 1. 下载代码，修改build.gradle, 升级其IDEA库到2019.1:
> 
> ```groovy
> intellij {
>     version = 'IU-2019.1'
>     pluginName = 'free-idea-mybatis'
>     plugins = ['coverage', 'Spring', 'DatabaseTools']
>     intellij.updateSinceUntilBuild false
> }
> ```
> 
> * 1. 修改`com.wuzhizhan.mybatis.action.MybatisTypedHandler.autoPopupParameter`:
> 
> ```java
>     private static void autoPopupParameter(final Project project, final Editor editor) {
>         AppUIExecutor.onUiThread().later().withDocumentsCommitted(project).inTransaction(project).execute(new Runnable() {
>             @Override
>             public void run() {
>                 new CodeCompletionHandlerBase(CompletionType.BASIC).invokeCompletion(project, editor, 1);
>             }
>         });
>     }
> ```
> 
> * 1. gradle jar可以成功生成jar包，安装到idea
> 
> 这样可以生成jar包，安装到idea后暂时可以正常使用。**但是build还是会失败**

新测有效，谢谢
