### ISSUE TITLE
自动生成带example接口报错，mybatis-generator-core-1.4.0.jar中没有org/mybatis/generator/api/dom/xml/Element类

### ISSUE THREAD

**Issue by ronallee** [wuzhizhan/free-idea-mybatis#107]
java.lang.NoClassDefFoundError: org/mybatis/generator/api/dom/xml/Element
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.mybatis.generator.internal.ObjectFactory.internalClassForName(ObjectFactory.java:150)
	at org.mybatis.generator.internal.ObjectFactory.createInternalObject(ObjectFactory.java:180)
	at org.mybatis.generator.internal.ObjectFactory.createPlugin(ObjectFactory.java:221)
	at org.mybatis.generator.config.Context.generateFiles(Context.java:483)
	at org.mybatis.generator.api.IntellijMyBatisGenerator.generate(IntellijMyBatisGenerator.java:262)
	at org.mybatis.generator.api.IntellijMyBatisGenerator.generate(IntellijMyBatisGenerator.java:181)
	at com.wuzhizhan.mybatis.generate.MybatisGenerator$1.run(MybatisGenerator.java:146)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1057)
	at com.wuzhizhan.mybatis.generate.MybatisGenerator.execute(MybatisGenerator.java:104)
	at com.wuzhizhan.mybatis.ui.MybatisGeneratorMainUI.onOK(MybatisGeneratorMainUI.java:542)
	at com.wuzhizhan.mybatis.ui.MybatisGeneratorMainUI.access$1900(MybatisGeneratorMainUI.java:42)
	at com.wuzhizhan.mybatis.ui.MybatisGeneratorMainUI$4.actionPerformed(MybatisGeneratorMainUI.java:482)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.mybatis.generator.api.dom.xml.Element PluginClassLoader[cn.wuzhizhan.plugin.mybatis, 2019.12.18] com.intellij.ide.plugins.cl.PluginClassLoader@60adf3e6
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 53 more

**Comment by JimmyLincole** [comment]
同遇到，请问，有解决了么？谢谢

**Comment by hdwmp123** [comment]
遇到同样的问题，求答案，微信 1301008570
