### ISSUE TITLE
生成 dao 方法报异常

### ISSUE THREAD

**Issue by jiming** [wuzhizhan/free-idea-mybatis#15]
我的 java 代码
 */
@Mapper
public interface CustomerMapper extends BaseCustomerMapper {

    int findMaxAllowedIpAddress();
}

我的 mapper 代码

<mapper namespace="com.dangdang.cmt.ipms.modules.customer.dao.CustomerMapper">

</mapper>

报异常：

Element cannot be added
com.intellij.util.IncorrectOperationException: Element cannot be added
	at com.intellij.psi.impl.source.tree.CompositePsiElement.a(CompositePsiElement.java:322)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.add(CompositePsiElement.java:151)
	at com.intellij.util.xml.impl.DomInvocationHandler.a(DomInvocationHandler.java:814)
	at com.intellij.util.xml.impl.DomInvocationHandler.addCollectionChild(DomInvocationHandler.java:787)
	at com.intellij.util.xml.impl.AddChildInvocation.invoke(AddChildInvocation.java:43)
	at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:681)
	at com.seventh7.mybatis.dom.model.Mapper$$EnhancerByJetBrainsMainCglib$$3d47d9c5.addSelect(<generated>)
	at com.seventh7.mybatis.generate.SelectGenerator.getTarget(SelectGenerator.java:25)
	at com.seventh7.mybatis.generate.StatementGenerator.setupTag(StatementGenerator.java:160)
	at com.seventh7.mybatis.generate.StatementGenerator.access$100(StatementGenerator.java:41)
	at com.seventh7.mybatis.generate.StatementGenerator$4.selected(StatementGenerator.java:148)
	at com.seventh7.mybatis.ui.UiComponentFacade$3.run(UiComponentFacade.java:117)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:934)
	at com.seventh7.mybatis.ui.UiComponentFacade.setActionForExecutableListener(UiComponentFacade.java:101)
	at com.seventh7.mybatis.ui.UiComponentFacade.access$000(UiComponentFacade.java:26)
	at com.seventh7.mybatis.ui.UiComponentFacade$4.run(UiComponentFacade.java:123)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1392)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by wuzhizhan** [comment]
已确认，目前在整体升级到兼容最新mybatis

**Comment by jiming** [comment]
谢谢啦！
