### ISSUE TITLE
Optional.get() cannot be called on an absent value

### ISSUE THREAD

**Issue by wangk258** [wuzhizhan/free-idea-mybatis#18]
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:49)
	at com.seventh7.mybatis.alias.InnerAliasResolver.<init>(InnerAliasResolver.java:20)
	at com.seventh7.mybatis.alias.AliasResolverFactory.createInnerAliasResolver(AliasResolverFactory.java:14)
	at com.seventh7.mybatis.alias.AliasFacade.initResolvers(AliasFacade.java:51)
	at com.seventh7.mybatis.alias.AliasFacade.<init>(AliasFacade.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:228)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:42)
	at com.seventh7.mybatis.alias.AliasFacade.getInstance(AliasFacade.java:32)
	at com.seventh7.mybatis.alias.AliasClassReference.resolve(AliasClassReference.java:35)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.hasBadResolve(XmlHighlightVisitor.java:553)
	at com.intellij.util.xml.highlighting.DomHighlightingHelperImpl.a(DomHighlightingHelperImpl.java:181)
	at com.intellij.util.xml.highlighting.DomHighlightingHelperImpl.checkResolveProblems(DomHighlightingHelperImpl.java:123)
	at com.intellij.util.xml.highlighting.BasicDomElementsInspection.checkDomElement(BasicDomElementsInspection.java:63)
	at com.seventh7.mybatis.inspection.MapperXmlInspection.checkDomElement(MapperXmlInspection.java:19)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:71)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:67)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkChildren(DomElementsInspection.java:87)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:70)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:67)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkChildren(DomElementsInspection.java:87)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:70)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:67)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkFileElement(DomElementsInspection.java:74)
	at com.intellij.util.xml.highlighting.DomElementAnnotationsManagerImpl.checkFileElement(DomElementAnnotationsManagerImpl.java:234)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkDomFile(DomElementsInspection.java:150)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkFile(DomElementsInspection.java:123)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:156)
	at com.intellij.psi.impl.source.xml.XmlFileImpl.accept(XmlFileImpl.java:74)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:305)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1147)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:63)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:316)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:226)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:132)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by wuzhizhan** [comment]
未设置sdk会出现
