### ISSUE TITLE
java.lang.NoClassDefFoundError: com/mysql/cj/conf/ConnectionUrlParser

### ISSUE THREAD

**Issue by a2020883119** [wuzhizhan/free-idea-mybatis#94]
java.lang.NoClassDefFoundError: com/mysql/cj/conf/ConnectionUrlParser
	at com.wuzhizhan.mybatis.generate.MybatisGenerator.execute(MybatisGenerator.java:84)
	at com.wuzhizhan.mybatis.ui.MybatisGeneratorMainUI.onOK(MybatisGeneratorMainUI.java:588)
	at com.wuzhizhan.mybatis.ui.MybatisGeneratorMainUI.access$1900(MybatisGeneratorMainUI.java:42)
	at com.wuzhizhan.mybatis.ui.MybatisGeneratorMainUI$4.actionPerformed(MybatisGeneratorMainUI.java:482)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:823)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.mysql.cj.conf.ConnectionUrlParser PluginClassLoader[cn.wuzhizhan.plugin.mybatis, 2019.11.27] com.intellij.ide.plugins.cl.PluginClassLoader@2081d993
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 44 more

**Comment by a2020883119** [comment]
今天刚更新的最新版本，我的idea是最新版本，数据库是mysql5.7，今天更新前不报错，今天更新后就没法用了，报这样的错，然后我又回退版本了~回退前一个版本又可以正常使用了，还需要什么信息可以告诉我，我尽量提供，~感谢你的这么优质的插件~加油~

**Comment by a2020883119** [comment]
回退前一个版本又可以正常使用了，还需要什么信息可以告诉我，我尽量提供，感谢你的这么优质的插件加油

**Comment by raulos-chan** [comment]
idea: 2017.3.7
mysql: 5.7
由v2019.11.16更新到v2019.11.27遇到同样问题；
对比了一下文件build.gradle，发现比之前的版本少了依赖：
compile group: 'org.xerial', name: 'sqlite-jdbc', version: '3.19.3'

重新加上依赖，编译打包，选择从本地磁盘安装打包后的zip重新安装插件，问题解决
