### ISSUE TITLE
java.lang.NoClassDefFoundError: com/mysql/cj/conf/ConnectionUrlParser

### ISSUE THREAD

**Issue by yulvyou** [wuzhizhan/free-idea-mybatis#95]
您好，在使用 Free Mybatis plugin 的过程中出现错误：

IDEA版本：2019.2
数据库及版本：MySQL 8.0
驱动：com.mysql.cj.jdbc.Driver

**问题**：
1、通过 mybatis generator gui 方法生成 model、dao 和 xml mapper 的时候报一下错误。

java.lang.NoClassDefFoundError: com/mysql/cj/conf/ConnectionUrlParser
	at com.wuzhizhan.mybatis.generate.MybatisGenerator.execute(MybatisGenerator.java:84)
	at com.wuzhizhan.mybatis.ui.MybatisGeneratorMainUI.onOK(MybatisGeneratorMainUI.java:542)

2、报问题1 的错误之后再次通过  mybatis generator gui 方法生成 model、dao 和 xml mapper 的时候，没有任何反应，也不提示错误。

望解答，谢谢！

**Comment by TIIEHenry** [comment]
我也遇到了，请问找到了解决方法吗？
