### ISSUE TITLE
生成代码异常：java.lang.NoClassDefFoundError: com/mysql/cj/conf/ConnectionUrlParser

### ISSUE THREAD

**Issue by sharp1229** [wuzhizhan/free-idea-mybatis#96]
环境：
Intellij IDEA: 2019.2
JDK: 1.8.0_221-b11
MySQL Connector/J: 8.0.18

异常信息如下：
java.lang.NoClassDefFoundError: com/mysql/cj/conf/ConnectionUrlParser
	at com.wuzhizhan.mybatis.generate.MybatisGenerator.execute(MybatisGenerator.java:84)
	at com.wuzhizhan.mybatis.ui.MybatisGeneratorMainUI.onOK(MybatisGeneratorMainUI.java:542)
	at com.wuzhizhan.mybatis.ui.MybatisGeneratorMainUI.access$1900(MybatisGeneratorMainUI.java:42)
	at com.wuzhizhan.mybatis.ui.MybatisGeneratorMainUI$4.actionPerformed(MybatisGeneratorMainUI.java:482)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:823)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.mysql.cj.conf.ConnectionUrlParser PluginClassLoader[cn.wuzhizhan.plugin.mybatis, 2019.11.27] com.intellij.ide.plugins.cl.PluginClassLoader@455bb443
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 44 more

**Comment by hytsli** [comment]
同样的异常

**Comment by 1515522027** [comment]
我也是

**Comment by exiuqa** [comment]
有解决办法了吗，我也是

**Comment by 1515522027** [comment]
没有啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "exiuqa"<notifications@github.com&gt;; 
发送时间: 2019年12月8日(星期天) 下午2:20
收件人: "wuzhizhan/free-idea-mybatis"<free-idea-mybatis@noreply.github.com&gt;; 
抄送: "稚生  ん"<1515522027@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [wuzhizhan/free-idea-mybatis] 生成代码异常：java.lang.NoClassDefFoundError: com/mysql/cj/conf/ConnectionUrlParser (#96)




有解决办法了吗，我也是

**Comment by BlogBD** [comment]
有解决了的吗？

**Comment by 1515522027** [comment]
没有啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"伟"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 晚上11:42
收件人:&nbsp;"wuzhizhan/free-idea-mybatis"<free-idea-mybatis@noreply.github.com&gt;;
抄送:&nbsp;"稚生  ん"<1515522027@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wuzhizhan/free-idea-mybatis] 生成代码异常：java.lang.NoClassDefFoundError: com/mysql/cj/conf/ConnectionUrlParser (#96)




有解决了的吗？
